name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from package.json
        id: extract_version
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found"
            exit 1
          fi
          VERSION=$(jq -r '.version' package.json)
          if [ -z "$VERSION" ]; then
            echo "Error: Failed to extract version"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 添加 Node.js 设置
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 验证 npm 配置
      - name: Verify npm configuration
        run: |
          npm config list
          npm cache verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            chb2024/pieces-os:${{ steps.extract_version.outputs.version }}
            chb2024/pieces-os:latest
